#!/bin/bash

echo "
export async function init(program) {
  const { handler } = await import('./handler.js');
  return { handler };
}
">index.js

cp "./dmt-install/package.json" .

if [ ! -L _dmt_deps ]; then
  ln -s ../_dmt_deps .
fi
